// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsI20gFRcLKTbwrG8m90OzHzlX8TEv_Us',
    appId: '1:496640424992:web:3390855279e8620f2a5045',
    messagingSenderId: '496640424992',
    projectId: 'flutter-journey-diary',
    authDomain: 'flutter-journey-diary.firebaseapp.com',
    databaseURL: 'https://flutter-journey-diary-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-journey-diary.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg6jy4j9L2Oni5yVfSFSHESv9rCW_LtXE',
    appId: '1:496640424992:android:5ea59eeaef7abb812a5045',
    messagingSenderId: '496640424992',
    projectId: 'flutter-journey-diary',
    databaseURL: 'https://flutter-journey-diary-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-journey-diary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpwAtE_ytHDojrRjmPR1ttQZDKsRBIE4s',
    appId: '1:496640424992:ios:80bd420d2eb356ae2a5045',
    messagingSenderId: '496640424992',
    projectId: 'flutter-journey-diary',
    databaseURL: 'https://flutter-journey-diary-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-journey-diary.appspot.com',
    iosClientId: '496640424992-lmlsmbks1re7s6eg5vvp2h3rjvb5t5o1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterJourneyDiary',
  );
}
